package com.simats.neoomfs.entity;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

/**
 * ClinicalDecision entity – Step 7, generated by the clinical decision engine.
 * Stores the final risk assessment, fitness decision, clinical alerts, and recommendations
 * as structured JSON text fields for flexible querying and PDF rendering.
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Entity
@Table(name = "clinical_decisions")
public class ClinicalDecision extends BaseEntity {

    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "patient_id", nullable = false, unique = true)
    private Patient patient;

    @Enumerated(EnumType.STRING)
    @Column(name = "risk_level", length = 20)
    private RiskLevel riskLevel;

    @Enumerated(EnumType.STRING)
    @Column(name = "fitness_decision", length = 20)
    private FitnessDecision fitnessDecision;

    // Numeric risk index (0–100) computed by RiskCalculator
    @Column(name = "risk_score")
    private Integer riskScore;

    // JSON array of alert messages generated by AlertGenerator
    @Column(name = "clinical_alerts", columnDefinition = "TEXT")
    private String clinicalAlerts;

    // JSON array of recommendation strings from RecommendationEngine
    @Column(name = "recommendations", columnDefinition = "TEXT")
    private String recommendations;

    // Free text for doctor override / additional notes
    @Column(name = "decision_notes", columnDefinition = "TEXT")
    private String decisionNotes;

    // Who generated the decision
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "generated_by_user_id")
    private User generatedBy;

    @Column(name = "generated_at")
    private LocalDateTime generatedAt;

    public enum RiskLevel {
        LOW, MODERATE, HIGH, VERY_HIGH
    }

    public enum FitnessDecision {
        FIT, REVIEW, CRITICAL
    }
}
